config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#top"
  get "/home/about", to: "home#about", as: "home_about"
  resources :books, only: [:create, :index, :show, :edit, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :book_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :name, uniqueness: true, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  
  

  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end


  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :correct_user, only: [:edit]

  def index
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end


  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
   params.require(:book).permit(:title, :body)
  end
  def correct_user
  @book = Book.find(params[:id])
  @user = @book.user
  redirect_to(books_path) unless @user == current_user
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :correct_user, only: [:edit]
  def index
    @users =User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(created_at: :desc)
    @book = Book.new

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
  @user = User.find(params[:id])
  redirect_to(user_path(current_user)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
  		  <% if @book.errors.any? %>
        <div id="error_explanation" class="container px-5 px-sm-0">
          <h3>
            <%= @book.errors.count %>
            errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
  		   <%= form_with model: @book, local: true do |f| %>
  		   <div class="form-group">
  		     <label for="title">Title</label><br>
  		     <%= f.text_field :title, id: "title", class: "form-control book-title" %>
  		   </div>
  		   <div class="form-group">
  		     <label for="option">Option</label><br>
  		     <%= f.text_area :body, id: "option", class: "form-control book-body" %>
  		   </div>
  		   <div class="form-group">
  		     <%= f.submit "Update Book", class: "btn btn-success"%>
  		   </div>
  		   <% end %>
  		   <%= link_to "Show", book_path(@book) %> |
  		   <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation" class="container px-5 px-sm-0">
  <h3>
    <%= @book.errors.count %>
    errors prohibited this obj from being saved:
  </h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 63, 63, format: "jpeg", fallback: "no_image.jpg", size: "63x63" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduciton</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="title">Title</label><br>
          <%= f.text_field :title, id: "title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="opinion">opinion</label><br>
          <%= f.text_area :body, id: "opinion", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>

              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title,  book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart already-favorite"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fas fa-heart no-favorite"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 63, 63, format: "jpeg", fallback: "no_image.jpg", size: "63x63" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local: true do |f| %>
        <div class="form-group">
          <label for="title">Title</label><br>
          <%= f.text_field :title, id: "title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="option">option</label><br>
          <%= f.text_area :body, id: "option", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>


      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>

              <td>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to @user.name, user_path(@user) %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book) %>
              </td>
              <td>
                <%=  @book.body %>
              </td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i class="fas fa-heart already-favorite"><%= @book.favorites.count %></i>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="fas fa-heart no-favorite"><%= @book.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= @book.book_comments.count %></p>
              </td>

              <% if @user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm  btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか", class: "btn btn-sm btn-danger"  %>
              </td>
              <% end %>
              
            </tr>
          </tbody>
        </table>
        <div class="comment container">
          <% @book.book_comments.each do |book_comment| %>
            <div class="comment-list row">
              <div class="comment-user col-1">
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to book_comment.user.name, user_path(book_comment.user) %>
              </div>
              <div class="col">
              <%= book_comment.comment %>
              <% if book_comment.user  == current_user %>
               <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, "data-confirm" => "本当に消しますか", class: "btn btn-sm btn-danger" %>
              <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="comment-form">
          <%= form_with(model: [@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "book-comment-area" %>
            <%= f.submit "送信" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/home/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav_item">
                <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>
              <% else %>
              <li>
                <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
              <% end %>
            </ul>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p id="notice">
      <%= flash[:notice] %>
    </p>
    <%= yield %>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5, px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
        <div id="error_explanation" class="container px-5 px-sm-0">
          <h3>
            <%= @user.errors.count %>
            errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= form_with model: @user, local: true do |f| %>
          <div class="form-group">
            <label for="name">Naame</label><br>
            <%= f.text_field :name, id: "name"%>
          </div>
          <div class="form-group">
            <label for="image">Image</label><br>
            <%= f.attachment_field :profile_image, id: "image" %>
          </div>
          <div class="form-group">
            <label for="introduciton">introduciton</label><br>
            <%= f.text_field :introduction, id: "introduciton" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation" class="container px-5 px-sm-0">
  <h3>
    <%= @book.errors.count %>
    errors prohibited this obj from being saved:
  </h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 63, 63, format: "jpeg", fallback: "no_image.jpg", size: "63x63" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduciton</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="title">Title</label><br>
          <%= f.text_field :title, id: "title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="opinion">opinion</label><br>
          <%= f.text_area :body, id: "opinion", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>


      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>

              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>

            </tr>
            <% end %>


          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<% if @book.errors.any? %>
<div id="error_explanation" class="container px-5 px-sm-0">
  <h3>
    <%= @book.errors.count %>
    errors prohibited this obj from being saved:
  </h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 63, 63, format: "jpeg", fallback: "no_image.jpg", size: "63x63" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="title">Title</label><br>
          <%= f.text_field :title, id: "title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="opinion">opinion</label><br>
          <%= f.text_area :body, id: "opinion", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>

              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title,  book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart already-favorite"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fas fa-heart no-favorite"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>